# Generated by Django 5.1.1 on 2024-11-29 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Quantidade",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "codigo_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="Nome",
                    ),
                ),
            ],
        ),
    ]
