# Generated by Django 5.1.1 on 2024-11-29 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producao", "0001_initial"),
        ("roupa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producao",
            name="roupa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="roupa.roupa"
            ),
        ),
    ]
